version: '3.8'

services:
  backend:
    build:
      context: ./pufeth-tracker-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pufeth_tracker_db
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./pufeth-tracker-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000
  db:
    image: postgres
    environment:
      POSTGRES_DB: pufeth_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
