version: '3.8'

services:
  backend:
    build:
      context: ./pufeth-tracker-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
  frontend:
    build:
      context: ./pufeth-tracker-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

